Repository thisames/wallet-project, pull requests merged in 2024-12, with the labels that each got.

#34 feat: implementacao primeira tela de criacao de wallet
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/phonereplay/wallet_project/DialogCopySeedsFragment.java
  app/src/main/java/com/phonereplay/wallet_project/MainActivity.java
  app/src/main/java/com/phonereplay/wallet_project/WalletCreateTask.java
  app/src/main/java/com/phonereplay/wallet_project/WalletLoadTask.java
  app/src/main/java/com/phonereplay/wallet_project/WelcomeActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/dialog_copy_seeds.xml
Labels: feature

#36 feat: add REVIEWER.md Code Reviewer Manual
  REVIEWER.md
Labels: documentation

#37 29 restringir a UI de configuracao de tempo de atualizacao de grafico para aceitar apenas de 1 a 10 2
  app/build.gradle.kts
  app/libs/WheelPicker-1.1.2.aar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/phonereplay/wallet_project/DialogSelectUpdateTimeGraph.java
  app/src/main/java/com/phonereplay/wallet_project/GraphBitcoinActivity.java
  app/src/main/java/com/phonereplay/wallet_project/GraphBitcoinConfig.java
  app/src/main/java/com/phonereplay/wallet_project/GraphConfig.java
  app/src/main/res/drawable/icon_arrow.xml
  app/src/main/res/drawable/rounded_button_background.xml
  app/src/main/res/layout/ac_preview.xml
  app/src/main/res/layout/activity_graph_config.xml
  settings.gradle.kts
Labels: documentation, feature, medium task

#23 Adicionar modal de configuracao na tela de grafico para escolher a velocidade de atualizacao do grafico
  app/build.gradle.kts
  app/libs/WheelPicker-1.1.2.aar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/phonereplay/wallet_project/DialogSelectUpdateTimeGraph.java
  app/src/main/java/com/phonereplay/wallet_project/GraphBitcoinActivity.java
  app/src/main/java/com/phonereplay/wallet_project/GraphBitcoinConfig.java
  app/src/main/java/com/phonereplay/wallet_project/GraphConfig.java
  app/src/main/java/com/phonereplay/wallet_project/MainActivity.java
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/icon_arrow.xml
  app/src/main/res/drawable/rounded_button_background.xml
  app/src/main/res/layout/ac_preview.xml
  app/src/main/res/layout/activity_graph_bitcoin.xml
  app/src/main/res/layout/activity_graph_config.xml
  settings.gradle.kts
Labels: feature, medium task

#45 38 ajustar icone de configuracao mais pra cima
  app/src/main/res/layout/activity_graph_bitcoin.xml
Labels: easy task, refactor

#46 44-uncouple-scheduled-button-in-dialogcopyseedsfragment
  app/src/main/java/com/phonereplay/wallet_project/DialogCopySeedsFragment.java
  app/src/main/java/com/phonereplay/wallet_project/DialogSelectUpdateTimeGraph.java
  app/src/main/java/com/phonereplay/wallet_project/WelcomeActivity.java
  app/src/main/java/com/phonereplay/wallet_project/components/ButtonStopwatch.java
  app/src/main/res/layout/activity_graph_config.xml
  app/src/main/res/layout/dialog_copy_seeds.xml
Labels: refactor

#49 48 implement way to get depending on environment MainNetParams or TestNet3Params
  app/build.gradle.kts
  app/src/main/java/com/phonereplay/wallet_project/DialogCopySeedsFragment.java
  app/src/main/java/com/phonereplay/wallet_project/DialogSelectUpdateTimeGraph.java
  app/src/main/java/com/phonereplay/wallet_project/NetParams.java
  app/src/main/java/com/phonereplay/wallet_project/WelcomeActivity.java
  app/src/main/java/com/phonereplay/wallet_project/components/ButtonStopwatch.java
  app/src/main/java/com/phonereplay/wallet_project/configuration/InitConfig.java
Labels: feature

#50 refactor: create WalletAbstraction and WalletAbstractionInterface to make code more responsibility
  app/src/main/java/com/phonereplay/wallet_project/MainActivity.java
  app/src/main/java/com/phonereplay/wallet_project/SecondFragment.java
  app/src/main/java/com/phonereplay/wallet_project/WalletAbstraction.java
  app/src/main/java/com/phonereplay/wallet_project/WalletAbstractionInterface.java
  app/src/main/java/com/phonereplay/wallet_project/WelcomeActivity.java
Labels: refactor

#51 feat: add abstract and refactor of Binance/network
  app/src/main/java/com/phonereplay/wallet_project/GraphBitcoinActivity.java
  app/src/main/java/com/phonereplay/wallet_project/SecondFragment.java
  app/src/main/java/com/phonereplay/wallet_project/WalletAbstraction.java
  app/src/main/java/com/phonereplay/wallet_project/WalletAbstractionInterface.java
  app/src/main/java/com/phonereplay/wallet_project/WelcomeActivity.java
  app/src/main/java/com/phonereplay/wallet_project/network/RetrofitClient.java
  app/src/main/java/com/phonereplay/wallet_project/network/binance/BinanceApi.java
  app/src/main/java/com/phonereplay/wallet_project/network/binance/BinanceClient.java
  app/src/main/res/layout/fragment_second.xml
Labels: refactor
