Repository thisames/wallet-project, pull requests merged in 2024-11, with the labels that each got.

#13 feat: add README.md
  README.md
Labels: documentation

#21 feat: add configuracao de Análise de Código Estático
  Makefile
  README.md
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: documentation

#27 translate project documentation to English
  README.md
Labels: documentation

#28 feat: added convertToMilliseconds function
  app/src/main/java/com/phonereplay/wallet_project/GraphConfig.java
Labels: good first issue, feature

#33 feat: adicionar criacao de wallet com Seed Phrases
  app/build.gradle.kts
  app/src/main/java/com/phonereplay/wallet_project/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  gradle/libs.versions.toml
Labels: feature
